stages:
  preprocess:
    cmd: python download_mnist.py
    outs:
      - mnist
    desc: "Download raw MNIST dataset files"

  train:
    cmd: python train.py
    deps:
      - mnist
      - download_mnist.py
      - train.py
    outs:
      - model_save_test.pkl
    metrics:
      - metrics.json
    desc: "Train the neural network model on MNIST data"

  serve:
    cmd: nohup python -u fast.py > server.log 2>&1 &
    deps:
      - model_save_test.pkl
      - fast.py
    outs:
      - server.log  # Log file as a plasceholder for 'weblink'
    desc: "Start FastAPI server to serve the model for predictions"

  test:
    cmd: python test_api.py
    deps:
      - server.log  # Depends on serve stage output to ensure server is running
    outs:
      - test_result.json
    desc: "Test the FastAPI server by sending a prediction request"

  kill_server:
    cmd: pkill uvicorn || true
    deps:
      - test_result.json  # Depends on test stage to ensure testing is complete
    desc: "Stop the FastAPI server by killing the Uvicorn process"
