name: FastAPI Predict CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    - name: Start FastAPI Server
      run: |
        python fast.py

      - name: Run curl test
        run: |
          curl -X POST http://localhost:7000/predict/ \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d '{"image_vector": ['$(printf '0.0,'%.0s {1..783})'0.0]}'

      - name: Kill FastAPI Server
        run: |
          pkill uvicorn
